### ISSUE TITLE
ReferenceError: Can't find variable: InlineStyler

### ISSUE THREAD

**Issue by adyz** [HugoGiraudel/inline-styler#1]
Can I use this on simple webpages?

If so doing

```
        var styler = new InlineStyler($(ev.target).parents('.page')[0].getAttribute('style'))
        var hasColor = styler.hasStyle('-webkit-overflow-scrolling');

        console.log(hasColor);
```

throws me this error: `ReferenceError: Can't find variable: InlineStyler` on Safari iOS at least and maybe other browsers too

**Comment by KittyGiraudel** [comment]
Hey there. 

How do you include the script exactly?

**Comment by adyz** [comment]
`<script src="vendor/plugins/inline-styler.js"></script>`

**Comment by KittyGiraudel** [comment]
Do you use the latest version of the script? Is the code from your original post the whole thing? Do you have something more to show me?

**Comment by adyz** [comment]
Yes, from here `https://raw.githubusercontent.com/HugoGiraudel/inline-styler/master/index.js`

**Comment by adyz** [comment]
On chrome works fine, on safari iOS9.3.1 I get this error. 
<img width="1192" alt="screen shot 2016-04-21 at 1 08 12 pm" src="https://cloud.githubusercontent.com/assets/611174/14705433/2f39af40-07c2-11e6-9118-151398c96796.png">

**Comment by adyz** [comment]
Now that you've got me testing, on android I get this: `
inline-styler.js:19 Uncaught SyntaxError: missing ) after argument list`
![screen shot 2016-04-21 at 1 10 14 pm](https://cloud.githubusercontent.com/assets/611174/14705494/87b70802-07c2-11e6-897f-61e649975565.png)

**Comment by adyz** [comment]
I guess this needs to be transformed to normal js, this is make to be transformed by something like babel or browserify, right?

**Comment by KittyGiraudel** [comment]
This is “normal JS”. `Array.prototype.reduce` is supported in all browsers since IE 9. However there seems to be a syntax error. Let me check.

**Comment by KittyGiraudel** [comment]
Ooooh. Yes. The arrow function. My bad. I'm on it.

**Comment by KittyGiraudel** [comment]
Should be fixed in 0.1.3: https://github.com/HugoGiraudel/inline-styler/releases/tag/0.1.3.

**Comment by KittyGiraudel** [comment]
Note, you seem to be using jQuery so you can rewrite your snippet like this:

``` js
var node = $(ev.target);
var parent = node && node.parents('.page');
var styler = new InlineStyler(parent.attr('style'))
var hasStyle = styler.hasStyle('-webkit-overflow-scrolling');
```

**Comment by adyz** [comment]
Ow, awesome! Works great now! Thank you for your time and for making this script, really helpful.

**Comment by KittyGiraudel** [comment]
Thank you for reporting the bug. :)
